version: '3.0'

volumes:
  config:

networks:
  supply-chain-network:
    external:
      name: supply-chain-network

services:

  rest-api:
      image: hyperledger/sawtooth-rest-api:1.0
      container_name: supply-rest-api
      hostname: rest-api
      expose:
        - 8008
      depends_on:
        - validator
      entrypoint: |
        sawtooth-rest-api -vv
        --connect tcp://validator:4004
        --bind rest-api:8008
      networks:
        - supply-chain-network

  apache-proxy:
    image: "httpd:2.4"
    container_name: apache-proxy
    hostname: apache-proxy
    volumes:
      - "./config:/usr/local/apache2/conf/"
    ports:
    - 443:443
    networks:
      - supply-chain-network
