# Create external Docker network: $ docker network create [OPTIONS] NETWORK

# $ docker network create --attachable supply-chain-network

version: '2.1'

networks:
  supply-chain-network:
    external:
      name: supply-chain-network

services:
  rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: supply-rest-api
    expose:
      - 8008
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vv
        --connect tcp://validator:4004
        --bind rest-api:8008
    networks:
      - supply-chain-network

  nginx-proxy:
    image: nginx-proxy
    container_name: nginx-proxy
    networks:
      - supply-chain-network
    ports:
      - 443:443